### ISSUE TITLE
App loading issue

### ISSUE THREAD

**Issue by billyz313** [waderoberts123/tethysapp-statistics_calc#2]
When I installed the app I had no errors, however when I restart tethys the statstics_calc app doesn't load and i get the following error in the log file:

```
2020-06-02 20:42:41,565 ERROR    The following error occurred while trying to import the controller function "statistics_calc.controllers.home":
 Traceback (most recent call last):
  File "./tethys_apps/base/app_base.py", line 76, in _resolve_ref_function
    module = __import__(module_name, fromlist=[function_name])
  File "/home/tethys/miniconda/envs/tethys/lib/python3.7/site-packages/tethysapp_statistics_calc-1-py3.7.egg/tethysapp/statistics_calc/controllers.py", line 24, in <module>
    import hydrostats as hs
AttributeError: type object 'Path' has no attribute 'home'

2020-06-02 20:42:41,565 ERROR    App tethysapp.statistics_calc not loaded because of an issue with loading urls:
Traceback (most recent call last):
  File "./tethys_apps/harvester.py", line 267, in _harvest_app_instances
    app_instance.url_patterns
  File "./tethys_apps/base/app_base.py", line 197, in url_patterns
    controller_function = self._resolve_ref_function(url_map.controller, 'controller', is_extension)
  File "./tethys_apps/base/app_base.py", line 81, in _resolve_ref_function
    raise e
  File "./tethys_apps/base/app_base.py", line 76, in _resolve_ref_function
    module = __import__(module_name, fromlist=[function_name])
  File "/home/tethys/miniconda/envs/tethys/lib/python3.7/site-packages/tethysapp_statistics_calc-1-py3.7.egg/tethysapp/statistics_calc/controllers.py", line 24, in <module>
    import hydrostats as hs
  File "./hydrostats/__init__.py", line 10, in <module>
    from hydrostats.analyze import *
  File "./hydrostats/analyze.py", line 15, in <module>
    import matplotlib.pyplot as plt
  File "./matplotlib/pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "./matplotlib/colorbar.py", line 31, in <module>
    import matplotlib.contour as contour
  File "./matplotlib/contour.py", line 16, in <module>
    import matplotlib.font_manager as font_manager
  File "./matplotlib/font_manager.py", line 103, in <module>
    os.path.join(str(Path.home()), r'AppData\Local\Microsoft\Windows\Fonts'),
AttributeError: type object 'Path' has no attribute 'home'
```
Any assistance would be helpful, thank you.

**Comment by billyz313** [comment]
I have resolved this issue by:
conda remove matplotlib
pip uninstall matplotlib
pip install matplotlib

This also affected Cycler in some way so i had to also:
pip uninstall Cycler
pip install Cycler
